#pragma once

#include "DecoratorTiled.h"

namespace Rml {

class DecoratorTiledImage : public DecoratorTiled {
public:
	DecoratorTiledImage();
	virtual ~DecoratorTiledImage();

	/// Initialises the tile for the decorator.
	/// @param tile[in] The declaration for the tile.
	/// @param texture[in] The texture to apply to the tile.
	/// @return True if the image is valid, false otherwise.
	bool Initialise(const Tile& tile, Texture texture);

	/// Called on a decorator to generate any required per-element data for a newly decorated element.
	DecoratorDataHandle GenerateElementData(Element* element, BoxArea paint_area) const override;
	/// Called to release element data generated by this decorator.
	void ReleaseElementData(DecoratorDataHandle element_data) const override;

	/// Called to render the decorator on an element.
	void RenderElement(Element* element, DecoratorDataHandle element_data) const override;

private:
	Tile tile;
};

class DecoratorTiledImageInstancer : public DecoratorTiledInstancer {
public:
	DecoratorTiledImageInstancer();
	~DecoratorTiledImageInstancer();

	/// Instances an image decorator.
	SharedPtr<Decorator> InstanceDecorator(const String& name, const PropertyDictionary& properties,
		const DecoratorInstancerInterface& instancer_interface) override;
};

} // namespace Rml
