#pragma once

#include "DecoratorTiled.h"

namespace Rml {

class DecoratorTiledVertical : public DecoratorTiled {
public:
	DecoratorTiledVertical();
	virtual ~DecoratorTiledVertical();

	/// Initialises the tiles for the decorator.
	/// @param[in] tiles The declaration for all three tiles.
	/// @param[in] textures The textures for the three tiles.
	/// @return True if all the tiles and textures are properly specified.
	bool Initialise(const Tile* tiles, const Texture* textures);

	/// Called on a decorator to generate any required per-element data for a newly decorated element.
	DecoratorDataHandle GenerateElementData(Element* element, BoxArea paint_area) const override;
	/// Called to release element data generated by this decorator.
	void ReleaseElementData(DecoratorDataHandle element_data) const override;

	/// Called to render the decorator on an element.
	void RenderElement(Element* element, DecoratorDataHandle element_data) const override;

private:
	enum { TOP, BOTTOM, CENTRE, COUNT };

	Tile tiles[COUNT];
};

class DecoratorTiledVerticalInstancer : public DecoratorTiledInstancer {
public:
	DecoratorTiledVerticalInstancer();
	~DecoratorTiledVerticalInstancer();

	/// Instances a vertical decorator.
	SharedPtr<Decorator> InstanceDecorator(const String& name, const PropertyDictionary& properties,
		const DecoratorInstancerInterface& instancer_interface) override;
};

} // namespace Rml
