#pragma once

#include <RmlUi/Core/Log.h>
#include <RmlUi/Core/Types.h>
#include <utility>

class SandboxLogger {
public:
	struct Message {
		Rml::Log::Type type;
		Rml::String text;
	};

	void Log(Rml::Log::Type type, const Rml::String& message)
	{
		if (suspended)
			return;

		// Discard the oldest messages when the backlog grows too large, so that a document producing warnings every
		// frame cannot exhaust memory.
		if (messages.size() >= max_messages)
			messages.erase(messages.begin(), messages.begin() + (messages.size() - max_messages) + 1);

		messages.push_back(Message{type, message});
	}

	Rml::Vector<Message> PopMessages() { return std::exchange(messages, {}); }

	/// Temporarily stop recording messages, used while the log itself is being submitted to the user interface to avoid
	/// feeding messages generated by that operation straight back into the log.
	void SetSuspended(bool value) { suspended = value; }

private:
	static constexpr size_t max_messages = 200;

	Rml::Vector<Message> messages;
	bool suspended = false;
};
