// Generated by compile_shaders.py using unknown version. Do not edit manually.
#pragma once

#include "shader_frag_blend_mask.h"
#include "shader_frag_blur.h"
#include "shader_frag_color.h"
#include "shader_frag_color_matrix.h"
#include "shader_frag_creation.h"
#include "shader_frag_drop_shadow.h"
#include "shader_frag_gradient.h"
#include "shader_frag_passthrough.h"
#include "shader_frag_texture.h"
#include "shader_vert.h"
#include "shader_vert_blur.h"
#include "shader_vert_passthrough.h"
