#pragma once

#include <RmlUi/Core/Decorator.h>

class DecoratorDefender : public Rml::Decorator {
public:
	virtual ~DecoratorDefender();

	bool Initialise(const Rml::Texture& texture);

	/// Called on a decorator to generate any required per-element data for a newly decorated element.
	Rml::DecoratorDataHandle GenerateElementData(Rml::Element* element, Rml::BoxArea paint_area) const override;
	/// Called to release element data generated by this decorator.
	void ReleaseElementData(Rml::DecoratorDataHandle element_data) const override;

	/// Called to render the decorator on an element.
	void RenderElement(Rml::Element* element, Rml::DecoratorDataHandle element_data) const override;

private:
	int image_index;
};

class DecoratorInstancerDefender : public Rml::DecoratorInstancer {
public:
	DecoratorInstancerDefender();
	~DecoratorInstancerDefender();

	/// Instances a decorator given the property tag and attributes from the RCSS file.
	Rml::SharedPtr<Rml::Decorator> InstanceDecorator(const Rml::String& name, const Rml::PropertyDictionary& properties,
		const Rml::DecoratorInstancerInterface& instancer_interface) override;

private:
	Rml::PropertyId id_image_src;
};
