#pragma once

#include <RmlUi/Core/Decorator.h>
#include <RmlUi/Core/Types.h>

class DecoratorStarfield : public Rml::Decorator {
public:
	virtual ~DecoratorStarfield();

	bool Initialise(int num_layers, const Rml::Colourb& top_colour, const Rml::Colourb& bottom_colour, float top_speed, float bottom_speed,
		int top_density, int bottom_density);

	/// Called on a decorator to generate any required per-element data for a newly decorated element.
	Rml::DecoratorDataHandle GenerateElementData(Rml::Element* element, Rml::BoxArea paint_area) const override;
	/// Called to release element data generated by this decorator.
	void ReleaseElementData(Rml::DecoratorDataHandle element_data) const override;

	/// Called to render the decorator on an element.
	void RenderElement(Rml::Element* element, Rml::DecoratorDataHandle element_data) const override;

private:
	int num_layers;
	Rml::Colourb top_colour;
	Rml::Colourb bottom_colour;
	float top_speed;
	float bottom_speed;
	int top_density;
	int bottom_density;

	struct StarLayer {
		typedef Rml::Vector<Rml::Vector2f> StarList;
		StarList stars;
		Rml::Colourb colour;
		float speed;
	};

	struct StarField {
		void Update(double t);
		double last_update;
		Rml::Vector2f dimensions;

		typedef Rml::Vector<StarLayer> StarLayerList;
		StarLayerList star_layers;
	};
};

class DecoratorInstancerStarfield : public Rml::DecoratorInstancer {
public:
	DecoratorInstancerStarfield();
	~DecoratorInstancerStarfield();

	/// Instances a decorator given the property tag and attributes from the RCSS file.
	Rml::SharedPtr<Rml::Decorator> InstanceDecorator(const Rml::String& name, const Rml::PropertyDictionary& properties,
		const Rml::DecoratorInstancerInterface& instancer_interface) override;

private:
	Rml::PropertyId id_num_layers, id_top_colour, id_bottom_colour, id_top_speed, id_bottom_speed, id_top_density, id_bottom_density;
};
